### PR TITLE
Cdk refactor

### PR DESCRIPTION
**Pull request by gadams999**
*Issue #, if available:*

None, internal rework.

*Description of changes:*

This is substantial change to the v2 accelerators. In mostly order of priority:

1. Refactored CDK L2 constructs to a common shared directory. Now different CDK projects can utilize the same constructs without having to duplicate.
2. Updated AWS provided Greengrass components. Nucleus now at 2.8.1.
3. Updated components dependencies for latest version of awsiotsdk.
4. Docker image for Greengrass now built locally instead of being pulled from a repo. AWS has stopped updating Nucleus versions in the Dockerfile. Easier to 
5. Added deployment strategy to `GreengrasV2Deployment` construct, allowing for keeping deployed components even if broken.
6. Bump all packages to latest version, including CDK to 2.249.0. No vulnerabilities identified.
7. Slightly changed build process for accelerators. Now `npm build` will not only build the current directories node modules, but also traverse and do the same for all used constructs. This helps ensure code development is consistent without TypeScript errors.
8. Refactored `simple_etl` to install all Python dependencies into the components working directories. This reduces collision with installing into `ggc_user` home (`--user`) location.
9. Started build script that exercises all accelerators and components to validate basic deployment, operation, and destruction. Note: this process takes upwards of 30 minutes to complete.
10. Other misc stuff.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by bvitali** [comment]
The description of point 4. seems to be incomplete:
4. Docker image for Greengrass now built locally instead of being pulled from a repo. AWS has stopped updating Nucleus versions in the Dockerfile. Easier to

**Comment by bvitali** [comment]
The "os_command" component produce an error. This is the log:

2022-11-09T20:21:32.877Z [INFO] (pool-2-thread-12) ggAccel.os_command: shell-runner-start. {scriptName=services.ggAccel.os_command.lifecycle.Install, serviceName=ggAccel.os_command, currentState=NEW, command=["python3.8 -m pip install -r /greengrass/v2/packages/artifacts-unarchived/ggAcc..."]}
2022-11-09T20:21:33.712Z [INFO] (Copier) ggAccel.os_command: stdout. Collecting awsiotsdk==1.11.9. {scriptName=services.ggAccel.os_command.lifecycle.Install, serviceName=ggAccel.os_command, currentState=NEW}
2022-11-09T20:21:33.715Z [INFO] (Copier) ggAccel.os_command: stdout. Using cached awsiotsdk-1.11.9-py3-none-any.whl (59 kB). {scriptName=services.ggAccel.os_command.lifecycle.Install, serviceName=ggAccel.os_command, currentState=NEW}
2022-11-09T20:21:34.831Z [INFO] (Copier) ggAccel.os_command: stdout. Collecting awscrt==0.14.7. {scriptName=services.ggAccel.os_command.lifecycle.Install, serviceName=ggAccel.os_command, currentState=NEW}
2022-11-09T20:21:34.850Z [INFO] (Copier) ggAccel.os_command: stdout. Using cached awscrt-0.14.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.5 MB). {scriptName=services.ggAccel.os_command.lifecycle.Install, serviceName=ggAccel.os_command, currentState=NEW}
2022-11-09T20:21:34.901Z [INFO] (Copier) ggAccel.os_command: stdout. Installing collected packages: awscrt, awsiotsdk. {scriptName=services.ggAccel.os_command.lifecycle.Install, serviceName=ggAccel.os_command, currentState=NEW}
2022-11-09T20:21:35.161Z [INFO] (Copier) ggAccel.os_command: stdout. Successfully installed awscrt-0.14.7 awsiotsdk-1.11.9. {scriptName=services.ggAccel.os_command.lifecycle.Install, serviceName=ggAccel.os_command, currentState=NEW}
2022-11-09T20:21:36.359Z [INFO] (pool-2-thread-12) ggAccel.os_command: shell-runner-start. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=STARTING, command=["echo \u0022Starting command processor\u0022\nexport PYTHONPATH=.\npython3.8 -u /greengrass..."]}
2022-11-09T20:21:36.385Z [INFO] (Copier) ggAccel.os_command: stdout. Starting command processor. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:36.557Z [WARN] (Copier) ggAccel.os_command: stderr. INFO:root:Arguments: Namespace(request_topic='gg-accel-base-greengrass-core-kzH8xKQc/os_command/request', response_topic='gg-accel-base-greengrass-core-kzH8xKQc/os_command/response'). {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:36.563Z [WARN] (Copier) ggAccel.os_command: stderr. INFO:awsiot.eventstreamrpc:<Connection at 0x7fe9e4e32130 /greengrass/v2/ipc.socket:0> connected. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:46.564Z [WARN] (Copier) ggAccel.os_command: stderr. Traceback (most recent call last):. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:46.567Z [WARN] (Copier) ggAccel.os_command: stderr. File "/greengrass/v2/packages/artifacts-unarchived/ggAccel.os_command/1.0.0/ggAccel.os_command/app.py", line 165, in <module>. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:46.568Z [WARN] (Copier) ggAccel.os_command: stderr. main(). {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:46.569Z [WARN] (Copier) ggAccel.os_command: stderr. File "/greengrass/v2/packages/artifacts-unarchived/ggAccel.os_command/1.0.0/ggAccel.os_command/app.py", line 157, in main. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:46.572Z [WARN] (Copier) ggAccel.os_command: stderr. client.subscribe(args.request_topic, iotcore.QOS.AT_MOST_ONCE, handler). {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:46.589Z [WARN] (Copier) ggAccel.os_command: stderr. File "/greengrass/v2/packages/artifacts-unarchived/ggAccel.os_command/1.0.0/ggAccel.os_command/greengrassipcsdk/iotcore.py", line 94, in subscribe. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:46.598Z [WARN] (Copier) ggAccel.os_command: stderr. raise ex. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:46.599Z [WARN] (Copier) ggAccel.os_command: stderr. File "/greengrass/v2/packages/artifacts-unarchived/ggAccel.os_command/1.0.0/ggAccel.os_command/greengrassipcsdk/iotcore.py", line 92, in subscribe. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:46.600Z [WARN] (Copier) ggAccel.os_command: stderr. future.result(self._timeout). {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:46.602Z [WARN] (Copier) ggAccel.os_command: stderr. File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 446, in result. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:46.603Z [WARN] (Copier) ggAccel.os_command: stderr. raise TimeoutError(). {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:46.603Z [WARN] (Copier) ggAccel.os_command: stderr. concurrent.futures._base.TimeoutError. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:46.606Z [INFO] (Copier) ggAccel.os_command: Run script exited. {exitCode=1, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:46.868Z [INFO] (pool-2-thread-26) ggAccel.os_command: shell-runner-start. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=STARTING, command=["echo \u0022Starting command processor\u0022\nexport PYTHONPATH=.\npython3.8 -u /greengrass..."]}
2022-11-09T20:21:46.883Z [INFO] (Copier) ggAccel.os_command: stdout. Starting command processor. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:47.016Z [WARN] (Copier) ggAccel.os_command: stderr. INFO:root:Arguments: Namespace(request_topic='gg-accel-base-greengrass-core-kzH8xKQc/os_command/request', response_topic='gg-accel-base-greengrass-core-kzH8xKQc/os_command/response'). {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:57.022Z [WARN] (Copier) ggAccel.os_command: stderr. Traceback (most recent call last):. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:57.024Z [WARN] (Copier) ggAccel.os_command: stderr. File "/greengrass/v2/packages/artifacts-unarchived/ggAccel.os_command/1.0.0/ggAccel.os_command/app.py", line 165, in <module>. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:57.027Z [WARN] (Copier) ggAccel.os_command: stderr. main(). {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:57.029Z [WARN] (Copier) ggAccel.os_command: stderr. File "/greengrass/v2/packages/artifacts-unarchived/ggAccel.os_command/1.0.0/ggAccel.os_command/app.py", line 156, in main. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:57.030Z [WARN] (Copier) ggAccel.os_command: stderr. client = iotcore.Client(). {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:57.036Z [WARN] (Copier) ggAccel.os_command: stderr. File "/greengrass/v2/packages/artifacts-unarchived/ggAccel.os_command/1.0.0/ggAccel.os_command/greengrassipcsdk/__init__.py", line 29, in __init__. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:57.036Z [WARN] (Copier) ggAccel.os_command: stderr. ipc_client = connect(). {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:57.037Z [WARN] (Copier) ggAccel.os_command: stderr. File "/greengrass/v2/work/ggAccel.os_command/awsiot/greengrasscoreipc/__init__.py", line 66, in connect. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:57.038Z [WARN] (Copier) ggAccel.os_command: stderr. connect_future.result(timeout). {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:57.038Z [WARN] (Copier) ggAccel.os_command: stderr. File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 446, in result. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:57.040Z [WARN] (Copier) ggAccel.os_command: stderr. raise TimeoutError(). {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:57.040Z [WARN] (Copier) ggAccel.os_command: stderr. concurrent.futures._base.TimeoutError. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:57.055Z [INFO] (Copier) ggAccel.os_command: Run script exited. {exitCode=1, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:57.461Z [INFO] (pool-2-thread-26) ggAccel.os_command: shell-runner-start. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=STARTING, command=["echo \u0022Starting command processor\u0022\nexport PYTHONPATH=.\npython3.8 -u /greengrass..."]}
2022-11-09T20:21:57.476Z [INFO] (Copier) ggAccel.os_command: stdout. Starting command processor. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:21:57.610Z [WARN] (Copier) ggAccel.os_command: stderr. INFO:root:Arguments: Namespace(request_topic='gg-accel-base-greengrass-core-kzH8xKQc/os_command/request', response_topic='gg-accel-base-greengrass-core-kzH8xKQc/os_command/response'). {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:22:07.612Z [WARN] (Copier) ggAccel.os_command: stderr. Traceback (most recent call last):. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:22:07.614Z [WARN] (Copier) ggAccel.os_command: stderr. File "/greengrass/v2/packages/artifacts-unarchived/ggAccel.os_command/1.0.0/ggAccel.os_command/app.py", line 165, in <module>. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:22:07.615Z [WARN] (Copier) ggAccel.os_command: stderr. main(). {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:22:07.616Z [WARN] (Copier) ggAccel.os_command: stderr. File "/greengrass/v2/packages/artifacts-unarchived/ggAccel.os_command/1.0.0/ggAccel.os_command/app.py", line 156, in main. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:22:07.619Z [WARN] (Copier) ggAccel.os_command: stderr. client = iotcore.Client(). {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:22:07.628Z [WARN] (Copier) ggAccel.os_command: stderr. File "/greengrass/v2/packages/artifacts-unarchived/ggAccel.os_command/1.0.0/ggAccel.os_command/greengrassipcsdk/__init__.py", line 29, in __init__. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:22:07.630Z [WARN] (Copier) ggAccel.os_command: stderr. ipc_client = connect(). {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:22:07.631Z [WARN] (Copier) ggAccel.os_command: stderr. File "/greengrass/v2/work/ggAccel.os_command/awsiot/greengrasscoreipc/__init__.py", line 66, in connect. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:22:07.632Z [WARN] (Copier) ggAccel.os_command: stderr. connect_future.result(timeout). {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:22:07.633Z [WARN] (Copier) ggAccel.os_command: stderr. File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 446, in result. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:22:07.635Z [WARN] (Copier) ggAccel.os_command: stderr. raise TimeoutError(). {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:22:07.636Z [WARN] (Copier) ggAccel.os_command: stderr. concurrent.futures._base.TimeoutError. {scriptName=services.ggAccel.os_command.lifecycle.Run.Script, serviceName=ggAccel.os_command, currentState=RUNNING}
2022-11-09T20:22:07.658Z [INFO] (Copier) ggAccel.os_command: Run script exited. {exitCode=1, serviceName=ggAccel.os_command, currentState=RUNNING}

**Comment by gadams999** [comment]
> The description of point 4. seems to be incomplete: 4. Docker image for Greengrass now built locally instead of being pulled from a repo. AWS has stopped updating Nucleus versions in the Dockerfile. Easier to

Extra stuff. Since AWS doesn't maintain the Dockerfile repo nor publish new versions to registries, using the local Dockerfile and building locally, while takes longer, is the only option to ensure versions match.

**Comment by gadams999** [comment]
Will look into the `os_cmd` not running.

**Comment by gadams999** [comment]
> Will look into the `os_cmd` not running.

Overall I cannot get the os_cmd accelerator to fail. There is a condition where if the Nucleus doesn't have a connection to IoT Core, the subscribe will fail and component exists. Recommend approving and merging the PR, then will open an issue on os_cmd.

**Comment by bvitali** [comment]
The os_cmd component sometimes doesn't work, it must be timing related. I'm ok to approve the pull request and reopen a new issue on os_cmd.

**Review by bvitali — COMMENTED** [review]
The os_cmd component sometimes doesn't work, it must be timing related. I'm ok to approve the pull request and reopen a new issue on os_cmd.

**Pull request closed without merging**
